--- !ruby/object:Settings 
assumed: 100000
character_space: alpha
characters: 
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
- A
- B
- C
- D
- E
- F
- G
- H
- I
- J
- K
- L
- M
- N
- O
- P
- Q
- R
- S
- T
- U
- V
- W
- X
- Y
- Z
max: 3
mix: 0
mode: normal
secret: d600474b1b8e50d3633c91c0cf1efc454b79c9624a43fd7de441ee71745726ab
sha: d600474b1b8e50d3633c91c0cf1efc454b79c9624a43fd7de441ee71745726ab
