--- !ruby/object:Settings 
alphas: 
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
- A
- B
- C
- D
- E
- F
- G
- H
- I
- J
- K
- L
- M
- N
- O
- P
- Q
- R
- S
- T
- U
- V
- W
- X
- Y
- Z
characters: &id001 
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
digits: *id001
max: 4
mix: 0
mode: digit
modes_semantic: 
secret: "3333"
specials: 
- "!"
- "\""
- "#"
- $
- "%"
- "&"
- "'"
- (
- )
- "*"
- +
- ","
- "-"
- .
- /
- !binary |
  wqc=

- "="
